---
- name: "1.1.1 Ensure 'Cross-origin HTTP Authentication prompts' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: AllowCrossOriginAuthPrompt
      data: 0
      type: dword

- name: "1.2.1 (L1) Ensure 'Configure the list of domains on which Safe Browsing will not trigger warnings' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SafeBrowsingAllowlistDomains
      data: 0
      type: dword  

- name: "1.2.2 (L1) Ensure 'Safe Browsing Protection Level' is set to 'Enabled: Standard Protection' or higher"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SafeBrowsingProtectionLevel
      data: 1
      type: dword     
      
- name: "1.3 (L1) Ensure 'Allow Google Cast to connect to Cast devices on all IP addresses' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: MediaRouterCastAllowAllIPs
      data: 0
      type: dword           
      
- name: "1.4 (L1) Ensure 'Allow queries to a Google time service' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: BrowserNetworkTimeQueriesEnabled
      data: 1
      type: dword                 
      
- name: "1.5 (L1) Ensure 'Allow the audio sandbox to run' is set to 'Enabled' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: AudioSandboxEnabled
      data: 1
      type: dword    
      
- name: "1.6 (L1) Ensure 'Ask where to save each file before downloading' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: PromptForDownloadLocation
      data: 1
      type: dword
      
- name: "1.7 (L1) Ensure 'Continue running background apps when Google Chrome is closed' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: BackgroundModeEnabled
      data: 0
      type: dword      
      
- name: "1.8 (L2) Ensure 'Control SafeSites adult content filtering' is set to 'Enabled: Filter top level sites (but not embedded iframes) for adult content' specified"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SafeSitesFilterBehavior
      data: 1
      type: dword   
      
- name: "1.9 (L1) Ensure 'Determine the availability of variations' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ChromeVariations
      data: 0
      type: dword         
      
- name: "1.10 (L1) Ensure 'Disable Certificate Transparency enforcement for a listof Legacy Certificate Authorities' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: CertificateTransparencyEnforcementDisabledForLegacyCas
      data: 0
      type: dword 
      
- name: "1.11 (L1) Ensure 'Disable Certificate Transparency enforcement for a list of subjectPublicKeyInfo hashes' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: CertificateTransparencyEnforcementDisabledForCas
      data: 0
      type: dword     
      
- name: "1.12 (L1) Ensure 'Disable Certificate Transparency enforcement for a list of URLs' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: CertificateTransparencyEnforcementDisabledForUrls
      data: 0
      type: dword           
      
- name: "1.13 (L1) Ensure 'Disable saving browser history' is set to 'Disabled' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SavingBrowserHistoryDisabled
      data: 0
      type: dword    
      
- name: "1.14 (L1) Ensure 'DNS interception checks enabled' is set to 'Enabled' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: DNSInterceptionChecksEnabled
      data: 1
      type: dword          
      
- name: "1.15 (L1) Ensure 'Enable component updatesin Google Chrome' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: DNSInterceptionChecksEnabled
      data: 1
      type: dword   
      
- name: "1.16 (L1) Ensure 'Enable globally scoped HTTP auth cache' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: GloballyScopeHTTPAuthCacheEnabled
      data: 0
      type: dword
      
- name: "1.17 (L1) Ensure 'Enable online OCSP/CRL checks' is set to 'Disabled' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: EnableOnlineRevocationChecks
      data: 0
      type: dword 
      
- name: "1.18 (L1) Ensure 'Enable Renderer Code Integrity' is set to 'Enabled' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: RendererCodeIntegrityEnabled
      data: 1
      type: dword
      
- name: "1.19 (L1) Ensure 'Enable security warnings for command-line flags' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: CommandLineFlagSecurityWarningsEnabled
      data: 1
      type: dword     
      
- name: "1.20 (L1) Ensure 'Enable third party software injection blocking' is set to'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ThirdPartyBlockingEnabled
      data: 1
      type: dword    
      
- name: "1.21 (L1) Ensure 'Enables managed extensions to use the Enterprise Hardware Platform API' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: EnterpriseHardwarePlatformAPIEnabled
      data: 0
      type: dword          
      
- name: "1.22 (L1) Ensure 'Ephemeral profile' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ForceEphemeralProfiles
      data: 0
      type: dword                
      
- name: "1.23 (L1) Ensure 'Import autofill form data from default browser on first run' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ImportAutofillFormData
      data: 0
      type: dword 
      
- name: "1.24 (L1) Ensure 'Import of homepage from default browser on first run' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ImportHomepage
      data: 0
      type: dword   
      
- name: "1.25 (L1) Ensure 'Import search engines from default browser on first run' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ImportSearchEngine
      data: 0
      type: dword    
      
- name: "1.26 (L1) Ensure 'List of names that will bypass the HSTS policy check' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: HSTSPolicyBypassList
      data: 0
      type: dword     
      
- name: "1.27 (L1) Ensure 'Origins or hostname patterns for which restrictions on insecure origins should not apply' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: OverrideSecurityRestrictionsOnInsecureOrigin
      data: 0
      type: dword  
      
- name: "1.28 (L1) Ensure 'Suppress lookalike domain warnings on domains' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: LookalikeWarningAllowlistDomains
      data: 0
      type: dword 
      
- name: "1.29 (L1) Ensure 'Suppressthe unsupported OS warning' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SuppressUnsupportedOSWarning
      data: 0
      type: dword  
      
- name: "1.30 (L1) Ensure 'URLs for which local IPs are exposed in WebRTC ICE candidates' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: WebRtcLocalIpsAllowedUrls
      data: 0
      type: dword 