---
- name: "3.1.1 (L2) Ensure 'Default cookies setting' is set to 'Enabled: Keep cookies for the duration of the session'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: DefaultCookiesSetting
      data: 4
      type: dword 
      
- name: "3.1.2 (L1) Ensure 'Default geolocation setting' is set to 'Enabled: Do not allow any site to track the users' physical location'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: DefaultGeolocationSetting
      data: 2
      type: dword     
      
- name: "3.2.1 (L1) Ensure 'Enable Google Cast' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: EnableMediaRouter
      data: 0
      type: dword 
      
- name: "3.3 (L1) Ensure 'Allow websites to query for available payment methods' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: PaymentMethodQueryEnabled
      data: 0
      type: dword    
      
- name: "3.4 (L1) Ensure 'Block third party cookies' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: BlockThirdPartyCookies
      data: 1
      type: dword          
      
- name: "3.5 (L2) Ensure 'Browser sign in settings' is set to 'Enabled: Disabled browser sign-in'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: BrowserSignin
      data: 0
      type: dword                
      
- name: "3.6 (L1) Ensure 'Control how Chrome Cleanup reports data to Google' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ChromeCleanupReportingEnabled
      data: 0
      type: dword 
      
- name: "3.7 (L1) Ensure 'Disable synchronization of data with Google' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SyncDisabled
      data: 1
      type: dword    
      
- name: "3.8 (L1) Ensure 'Enable alternate error pages' is set to 'Disabled' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: AlternateErrorPagesEnabled
      data: 0
      type: dword          
      
- name: "3.9 (L1) Ensure 'Enabledeleting browser and download history' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: AllowDeletingBrowserHistory
      data: 0
      type: dword        
      
- name: "3.10 (L1) Ensure 'Enable network prediction' is set to 'Enabled: Do not predict actions on any network connection'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: NetworkPredictionOptions
      data: 2
      type: dword              
      
- name: "3.11 (L1) Ensure 'Enable or disable spell checking web service' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SpellCheckServiceEnabled
      data: 0
      type: dword                    
      
- name: "3.12 (L1) Ensure 'Enable reporting of usage and crash-related data' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: MetricsReportingEnabled
      data: 0
      type: dword    
      
- name: "3.13 (L1) Ensure 'Enable Safe Browsing for trusted sources' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SafeBrowsingForTrustedSourcesEnabled
      data: 0
      type: dword  
      
- name: "3.14 (L2) Ensure 'Enable search suggestions' is set to 'Disabled' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SearchSuggestEnabled
      data: 0
      type: dword  
      
- name: "3.15 (L2) Ensure 'Enable Translate' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: TranslateEnabled
      data: 0
      type: dword 