---
- name: "4.1.1 (L2) Ensure 'Allow or deny screen capture' is set to 'Disabled' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ScreenCaptureAllowed
      data: 0
      type: dword    
      
- name: "4.2.1 (L2) Ensure 'Control use of the Serial API' is set to 'Enable: Do not allow any site to request access to serial ports via the Serial API' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: DefaultSerialGuardSetting
      data: 2
      type: dword          
      
- name: "4.2.2 (L2) Ensure 'Default Sensors Setting' is set to 'Enabled: Do not allow any siteto access sensors"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: DefaultSensorsSetting
      data: 2
      type: dword  
      
- name: "4.3.1 (L1) Ensure 'Enable submission of documents to Google Cloud print' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: CloudPrintSubmitEnabled
      data: 0
      type: dword    
      
- name: "4.4 (L2) Ensure 'Allow invocation of file selection dialogs' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: AllowFileSelectionDialogs
      data: 0
      type: dword   
      
- name: "4.5 (L2) Ensure 'Allow or deny audio capture' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: AudioCaptureAllowed
      data: 0
      type: dword         
      
- name: "4.6 (L2) Ensure 'Allow or deny video capture' is set to 'Disabled' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: VideoCaptureAllowed
      data: 0
      type: dword   
      
- name: "4.7 (L1) Ensure 'Allow user feedback' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: UserFeedbackAllowed
      data: 0
      type: dword       
      
- name: "4.8 (L2) Ensure Controls the mode of DNS-over-HTTPS is set to Enabled: secure"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: DnsOverHttpsMode
      data: secure
      type: string  
      
- name: "4.9 (L1) Ensure 'Enable AutoFill for addresses' is set to 'Disabled' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: AutofillAddressEnabled
      data: 0
      type: dword 
      
- name: "4.10 (L1) Ensure 'Enable AutoFill for credit cards' is set to 'Disabled' "
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: AutofillCreditCardEnabled
      data: 0
      type: dword       
      
- name: "4.11 (L1) Ensure 'Import saved passwords from default browser on first run' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ImportSavedPasswords
      data: 0
      type: dword     
      
- name: "4.12 (L1) Ensure 'List of types that should be excluded from synchronization' is set to 'Enabled: passwords'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SyncTypesListDisabled
      data: passwords
      type: string    