---

- name: 1.1 (L1) Ensure web content is on non-system partition (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-ItemProperty "IIS:\Sites\Default Web Site" -name physicalPath -value "C:\inetpub\wwwroot\"

- name: 1.3 (L1) Ensure 'directory browsing'  is set to disabled (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -Filter system.webserver/directorybrowse -PSPath iis:\-Name Enabled  -Value False

- name: 1.4 (L1) Ensure 'application pool identity' is configured for all application pools (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter 'system.applicationHost/applicationPools/add[@name='{{ apppool_name }}']/processModel' -name 'identityType' -value 'ApplicationPoolIdentity'

- name: "1.6 - Ensure 'application pool identity' is configured for anonymous user identity" # TODO: This may be default behaviour. Unable to confirm at this time.
  community.windows.win_xml:
    path: 'C:\Windows\System32\inetsrv\config\applicationHost.config'
    xpath: '/configuration/system.webServer/security/authentication/anonymousAuthentication[@userName]'
    type: attribute
    attribute: userName
    fragment: ""

- name: "1.7 - Ensure WebDav feature is disabled"
  ansible.windows.win_feature:
    name: Web-DAV-Publishing
    state: absent

- name: 2.1 (L1) Ensure 'global authorization rule' is set to restrict access (Not Scored)
  ansible.windows.win_powershell:
    script: |
      Remove-WebConfigurationProperty  -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.webServer/security/authorization" -name "." -AtElement @{users='*';roles='';verbs=''}
      Add-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.webServer/security/authorization" -name "." -value @{accessType='Allow';roles='Administrators'}

- name: 2.3 (L1) Ensure 'forms authentication' require SSL (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST/Default Web Site'  -filter 'system.web/authentication/forms' -name 'requireSSL' -value 'True'

- name: 2.4 (L2) Ensure 'forms authentication' is set to use cookies (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST/Default Web Site'  -filter 'system.web/authentication/forms' -name 'cookieless' -value 'UseCookies'

- name: "3.1 - Ensure 'deployment method retail' is set"
  community.windows.win_xml:
    path: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config'
    xpath: '/configuration/system.web'
    fragment: '<deployment retail="true"/>'

- name: 3.8 (L2) Ensure 'MachineKey validation method - .Net 3.5' is configured (Scored)
  ansible.windows.win_command: C:\Windows\system32\inetsrv\appcmd set config /commit:WEBROOT /section:machineKey /validation:SHA1 

- name: 3.9 (L1) Ensure 'MachineKey validation method -.Net 4.5'  is configured (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT'  -filter "system.web/machineKey" -name "validation" -value "AES"

- name: 3.10 (L1) Ensure global .NET trust level is configured  (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT'  -filter "system.web/trust" -name "level" -value "Medium"

- name: "3.11 - Ensure X-Powered-By Header is removed"
  community.windows.win_xml:
    path: 'C:\Windows\System32\inetsrv\config\applicationHost.config'
    xpath: '/configuration/system.webServer/httpProtocol/customHeaders/add[@name="X-Powered-By"]'
    state: absent

- name: "3.12 - Ensure Server Header is removed"
  community.windows.win_xml:
    path: 'C:\Windows\System32\inetsrv\config\applicationHost.config'
    xpath: '/configuration/system.webServer/security/requestFiltering'
    type: attribute
    attribute: removeServerHeader
    fragment: true

- name: 4.1 (L2) Ensure 'maxAllowedContentLength' is configured (Not Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.webServer/security/requestFiltering/requestLimits" -name "maxAllowedContentLength" -value 30000000        

- name: 4.2 (L2) Ensure 'maxURL request filter' is configured (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.webServer/security/requestFiltering/requestLimits" -name "maxUrl" -value 4096

- name: 4.3 (L2) Ensure 'MaxQueryString request filter' is configured  (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.webServer/security/requestFiltering/requestLimits" -name "maxQueryString" -value 2048

- name: 4.4 (L2) Ensurenon-ASCII  characters in URLs are not allowed (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.webServer/security/requestFiltering" -name "allowHighBitCharacters" -value "False"      

- name: 4.5 (L1) Ensure Double-Encoded  requests will be rejected (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.webServer/security/requestFiltering" -name "allowDoubleEscaping" -value "True"

- name: "4.6 - Ensure 'HTTP Trace Method' is disabled"
  ansible.windows.win_command: |
    C:\Windows\system32\inetsrv\appcmd set config /section:requestfiltering /+verbs.[verb='TRACE',allowed='false']
  register: result
  failed_when:
    - result.rc != 0
    - result.rc != 183
  # This command doesn't have a pre-check, so return code 0 is a success, and 183 (already exists) is a success. Anything else is failure.
  changed_when: result.rc == 0

- name: 4.7 (L1) Ensure Unlisted File Extensions are not allowed (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.webServer/security/requestFiltering/fileExtensions" -name "allowUnlisted" -value "False"

- name: 4.8 (L1) Ensure Handler is not granted Write and  Script/Execute (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.webServer/handlers" -name "accessPolicy" -value "Read,Script"

- name: 4.9 (L1) Ensure 'notListedIsapisAllowed' is set to false (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.webServer/security/isapiCgiRestriction" -name "notListedIsapisAllowed" -value "False"

- name: 4.10 (L1) Ensure 'notListedCgisAllowed' is set to false (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.webServer/security/isapiCgiRestriction" -name "notListedCgisAllowed" -value "False"

- name: 4.11 (L1) Ensure 'Dynamic  IP Address Restrictions' is enabled (Not Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.webServer/security/dynamicIpSecurity/denyByConcurrentRequests" -name "enabled" -value "True"
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.webServer/security/dynamicIpSecurity/denyByConcurrentRequests" -name "maxConcurrentRequests" -value {{ number_of_requests }}

- name: 5.1 (L1) Ensure Default IIS web log location is moved (Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/sites/siteDefaults/logFile" -name "directory" -value {{ new_log_location }}

- name: 5.2 (L1) Ensure Advanced IIS logging is enabled (Scored)
  ansible.windows.win_powershell:
    script: |
      Add-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.applicationHost/sites/siteDefaults/logFile/customFields" -name "." -value @{logFieldName='X-Forwarded-For';sourceName='X-Forwarded-For';sourceType='RequestHeader'}

- name: 6.1 (L1) Ensure FTP requests are encrypted (Not Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/sites/siteDefaults/ftpServer/security/ssl" -name "controlChannelPolicy" -value "SslRequire"
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/sites/siteDefaults/ftpServer/security/ssl" -name "dataChannelPolicy" -value "SslRequire"

- name: 6.2 (L1) Ensure FTP Logon  attempt restrictions is enabled (Not Scored)
  ansible.windows.win_powershell:
    script: |
      Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.ftpServer/security/authentication/denyByFailure" -name "enabled" -value "True"

- name: 7.1 (L2) Ensure HSTS Header is set (Not Scored)
  ansible.windows.win_command: C:\Windows\system32\inetsrv\appcmd.exe set config - section:system.webServer/httpProtocol /+"customHeaders.[name='Strict-Transport-Security',value='max-age=480; preload']"

- name: 7.2 (L1) Ensure SSLv2 is Disabled (Scored)
  ansible.windows.win_powershell:
    script: |
      New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server' -Force | Out-Null
      New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client' -Force| Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server' -name 'DisabledByDefault' -value '1' -PropertyType 'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client' -name 'DisabledByDefault' -value '1' -PropertyType 'DWord' -Force | Out-Null

- name: 7.3 (L1) Ensure SSLv3 is Disabled (Scored)
  ansible.windows.win_powershell:
    script: |
      New-Item'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server' -Force | Out-Null
      New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client' -Force | Out-Null
      New-ItemProperty -path'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server' -name 'DisabledByDefault' -value '1' -PropertyType'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client' -name 'DisabledByDefault' -value '1' -PropertyType 'DWord' -Force | Out-Null

- name: 7.4 (L1) Ensure TLS 1.0 is Disabled (Scored)
  ansible.windows.win_powershell:
    script: |
      New-Item'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server' -Force | Out-Null
      New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client' -Force | Out-Null
      New-ItemProperty -path'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server' -name 'DisabledByDefault' -value '1' -PropertyType'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client' -name 'DisabledByDefault' -value '1' -PropertyType 'DWord' -Force | Out-Null

- name: 7.5 (L1) Ensure TLS 1.1 is Disabled (Scored)
  ansible.windows.win_powershell:
    script: |
      New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server' -Force | Out-Null
      New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server' -name 'DisabledByDefault' -value '1' -PropertyType 'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client' -name 'DisabledByDefault' -value '1' -PropertyType 'DWord' -Force | Out-Null

- name: 7.6 (L1) Ensure TLS 1.2 is Enabled (Scored)
  ansible.windows.win_powershell:
    script: |
      New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server' -name 'Enabled' -value '1' -PropertyType 'DWord' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server' -name 'DisabledByDefault' -value '0' -PropertyType 'DWord' -Force | Out-Null

- name: 7.7 (L1) Ensure NULL Cipher Suites is Disabled (Scored)
  ansible.windows.win_powershell:
    script: |
      New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\NULL' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\NULL' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null

- name: 7.8 (L1) Ensure DES Cipher Suites is Disabled (Scored)
  ansible.windows.win_powershell:
    script: |
      (Get-Item 'HKLM:\').OpenSubKey('SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers', $true).CreateSubKey('DES 56/56')
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\DES 56/56' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null

- name: 7.9 (L1) Ensure RC4 Cipher Suites is Disabled (Scored)
  ansible.windows.win_powershell:
    script: |
      (Get-Item 'HKLM:\').OpenSubKey('SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers', $true).CreateSubKey('RC4 40/128')
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 40/128' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
      (Get-Item 'HKLM:\').OpenSubKey('SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers', $true).CreateSubKey('RC4 56/128')
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 56/128' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
      (Get-Item 'HKLM:\').OpenSubKey('SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers', $true).CreateSubKey('RC4 64/128')
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 64/128' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
      (Get-Item 'HKLM:\').OpenSubKey('SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers', $true).CreateSubKey('RC4 128/128')
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 128/128' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null

- name: 7.10 (L1) Ensure AES 128/128 Cipher Suite is Disabled (Scored)
  ansible.windows.win_powershell:
    script: |
      (Get-Item 'HKLM:\').OpenSubKey('SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers', $true).CreateSubKey('AES 128/128')
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 128/128' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null

- name: 7.11 (L1) Ensure AES 256/256 Cipher Suite is Enabled (Scored)
  ansible.windows.win_powershell:
    script: |
      (Get-Item 'HKLM:\').OpenSubKey('SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers', $true).CreateSubKey('AES 256/256')
      New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 256/256' -name 'Enabled' -value '1' -PropertyType 'DWord' -Force | Out-Null

- name: 7.12 (L2) Ensure TLS Cipher Suite ordering is Configured (Scored)
  ansible.windows.win_powershell:
    script: |
      New-Item'HKLM:\SOFTWARE\Policies\Microsoft\Cryptography\Configuration\SSL\00010002' -Force | Out-Null
      New-ItemProperty -path 'HKLM:\SOFTWARE\Policies\Microsoft\Cryptography\Configuration\SSL\00010002' -name 'Functions' -value 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256' -PropertyType 'MultiString' -Force | Out-Null              
